### ISSUE TITLE
distributed tensorlayer debug

### ISSUE THREAD

**Issue by li-zemin** [tensorlayer/tensorlayer#571]
### Issue Description

Hello:
I run the [example/tutorial_mnist_distributed.py](https://github.com/tensorlayer/tensorlayer/blob/master/example/tutorial_mnist_distributed.py)，I construct a distributed tensorlayer system consist of 3 GPU Servers.
The roles of 3 GPU server as follows:

> "ps": ["192.168.0.225:3001"]
>  "worker": ["192.168.0.90:3002", "192.168.0.134:3003"]

#### 1st Step: I run the scripts on worker1(master as well)
The command of worker1 is:
```sh
CUDA_VISIBLE_DEVICES=0 TF_CONFIG='{"cluster": {"ps": ["192.168.0.225:3001"], "worker": ["192.168.0.90:3002", "192.168.0.134:3003"]}, "task": {"type": "worker", "index": 0}}' python distribute_training.py
```

The console of worker1 is:
```sh
2018-05-15 15:49:00.189788: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-05-15 15:49:00.310136: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-05-15 15:49:00.310471: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:01:00.0
totalMemory: 7.92GiB freeMemory: 7.51GiB
2018-05-15 15:49:00.310500: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
E0515 15:49:00.379189612   32742 ev_epoll1_linux.c:1051]     grpc epoll fd: 24
2018-05-15 15:49:00.382999: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job ps -> {0 -> 192.168.0.225:3001}
2018-05-15 15:49:00.383040: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job worker -> {0 -> localhost:3002, 1 -> 192.168.0.134:3003}
2018-05-15 15:49:00.383417: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:324] Started server with target: grpc://localhost:3002
[TL] Load or Download MNIST > data/mnist
[TL] data/mnist/train-images-idx3-ubyte.gz
[TL] data/mnist/t10k-images-idx3-ubyte.gz
[TL] InputLayer  input: (?, 784)
[TL] DropoutLayer drop1: keep:0.800000 is_fix:False
[TL] DenseLayer  relu1: 800 relu
[TL] DropoutLayer drop2: keep:0.500000 is_fix:False
[TL] DenseLayer  relu2: 800 relu
[TL] DropoutLayer drop3: keep:0.500000 is_fix:False
[TL] DenseLayer  output: 10 identity
2018-05-15 15:49:10.962409: I tensorflow/core/distributed_runtime/master.cc:221] CreateSession still waiting for response from worker: /job:ps/replica:0/task:0
2018-05-15 15:49:20.962588: I tensorflow/core/distributed_runtime/master.cc:221] CreateSession still waiting for response from worker: /job:ps/replica:0/task:0
2018-05-15 15:49:30.962717: I tensorflow/core/distributed_runtime/master.cc:221] CreateSession still waiting for response from worker: /job:ps/replica:0/task:0
2018-05-15 15:49:40.962998: I tensorflow/core/distributed_runtime/master.cc:221] CreateSession still waiting for response from worker: /job:ps/replica:0/task:0
......
......
(continuing)

```
------
#### 2nd Step, I run the worker2

The command is:
```sh
CUDA_VISIBLE_DEVICES=0 TF_CONFIG='{"cluster": {"ps": ["192.168.0.225:3001"], "worker": ["192.168.0.90:3002", "192.168.0.134:3003"]}, "task": {"type": "worker", "index": 1}}' python distribute_training.py
```

The console info is:
```sh
2018-05-15 15:49:08.531928: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-05-15 15:49:08.641486: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-05-15 15:49:08.641709: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:01:00.0
totalMemory: 7.92GiB freeMemory: 75.94MiB
2018-05-15 15:49:08.641726: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-05-15 15:49:08.642951: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 75.94M (79626240 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E0515 15:49:08.643870142   10249 ev_epoll1_linux.c:1051]     grpc epoll fd: 24
2018-05-15 15:49:08.647220: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job ps -> {0 -> 192.168.0.225:3001}
2018-05-15 15:49:08.647246: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job worker -> {0 -> 192.168.0.90:3002, 1 -> localhost:3003}
2018-05-15 15:49:08.647643: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:324] Started server with target: grpc://localhost:3003
[TL] Load or Download MNIST > data/mnist
[TL] data/mnist/train-images-idx3-ubyte.gz
[TL] data/mnist/t10k-images-idx3-ubyte.gz
[TL] InputLayer  input: (?, 784)
[TL] DropoutLayer drop1: keep:0.800000 is_fix:False
[TL] DenseLayer  relu1: 800 relu
[TL] DropoutLayer drop2: keep:0.500000 is_fix:False
[TL] DenseLayer  relu2: 800 relu
[TL] DropoutLayer drop3: keep:0.500000 is_fix:False
[TL] DenseLayer  output: 10 identity
2018-05-15 15:49:19.205367: I tensorflow/core/distributed_runtime/master.cc:221] CreateSession still waiting for response from worker: /job:ps/replica:0/task:0
2018-05-15 15:49:29.205454: I tensorflow/core/distributed_runtime/master.cc:221] CreateSession still waiting for response from worker: /job:ps/replica:0/task:0
2018-05-15 15:49:39.205600: I tensorflow/core/distributed_runtime/master.cc:221] CreateSession still waiting for response from worker: /job:ps/replica:0/task:0
2018-05-15 15:49:49.205807: I tensorflow/core/distributed_runtime/master.cc:221] CreateSession still waiting for response from worker: /job:ps/replica:0/task:0
2018-05-15 15:49:59.205917: I tensorflow/core/distributed_runtime/master.cc:221] CreateSession still waiting for response from worker: /job:ps/replica:0/task:0
2018-05-15 15:50:09.206017: I tensorflow/core/distributed_runtime/master.cc:221] CreateSession still waiting for response from worker: /job:ps/replica:0/task:0
2018-05-15 15:50:19.206121: I tensorflow/core/distributed_runtime/master.cc:221] CreateSession still waiting for response from worker: /job:ps/replica:0/task:0
.......
.......
```
------

#### 3rd Step, I run the parameter server
The Command of ps is:
```sh
CUDA_VISIBLE_DEVICES=0 TF_CONFIG='{"cluster": {"ps": ["192.168.0.225:3001"], "worker": ["192.168.0.90:3002", "192.168.0.134:3003"]}, "task": {"type": "ps", "index": 0}}' python tutorial_mnist_distributed.py
```

And the console info on ps server is:
```sh
[lizemin@localhost pyProject]$ CUDA_VISIBLE_DEVICES=0 TF_CONFIG='{"cluster": {"ps": ["192.168.0.225:3001"], "worker": ["192.168.0.90:3002", "192.168.0.134:3003"]}, "task": {"type": "ps", "index": 0}}' python distribute_training.py
2018-05-15 03:49:20.271424: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-05-15 03:49:20.358919: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-05-15 03:49:20.359260: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:01:00.0
totalMemory: 7.93GiB freeMemory: 7.73GiB
2018-05-15 03:49:20.359291: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
E0515 03:49:20.393866172   27528 ev_epoll1_linux.c:1051]     grpc epoll fd: 25
2018-05-15 03:49:20.398410: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job ps -> {0 -> localhost:3001}
2018-05-15 03:49:20.398449: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job worker -> {0 -> 192.168.0.90:3002, 1 -> 192.168.0.134:3003}
2018-05-15 03:49:20.399022: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:324] Started server with target: grpc://localhost:3001

```

 As we see, the ps was not run correctly, I want to the reason.

The ps was in silent, could anyone can give me a tips to solve this problem, I have tried my best to settle it !!!

**Comment by DEKHTIARJonathan** [comment]
Could you please format correctly your message. It is unreadable.

Please have a look to how you should format code and logs in markdown.

**Comment by li-zemin** [comment]
Thank you very much, can you do me a favor? @zsdonghao Thanks!

**Comment by jorgemf** [comment]
@li-zemin The log you provided doesn't say anything. How do you run the programs? I need to know the command line used to start the training. PS usually doesn't output very much to the console, so not seeing anything doesn't mean they are not working

**Comment by li-zemin** [comment]
@jorgemf Thank you for your reply, I described my problem in detail, and format it in markdown.
Thank you for your help!

**Comment by jorgemf** [comment]
@li-zemin the PS seems ok, so there is an issue in the communication between the workers and the PS. It could be the port is closed or something like that. I also see the first worker prints the parameters of the network and if you see the code it shouldn't do it. Have you tried to run everything in the same machine without using a GPU? It will help to know whether is a network issue or something else

**Comment by li-zemin** [comment]
@jorgemf Thanks for your recommendation. I solved this problem by installing grpcio and grpc-tools with pip, and tested GRPC before running this example. 
More information in:
http://www.grpc.io/docs/quickstart/python.html#download-the-example

Besides, I forbide the ipv6 service in order to gaurantee that the grpc service runs in ipv4 correctly. Meanwhile, the impact of firewall should be excluded.

And, after running the demo, I found that the two workers create respective session, and the training process was finished by each of themselves. There is no "division of work" in the process between the two workers.

I am not sure whether I understand it correctly. And how I change this demo to solve the problem that single gpu server can't run a big model with large number of parameters.
Thanks!

**Comment by DEKHTIARJonathan** [comment]
Maybe we can make sure that the libraries `grpcio` and `grpc-tools` are installed when calling `tl.distributed`. Would this help and solve the issue ?

**Comment by lgarithm** [comment]
We implemented a helper command to launch distributed training, which is installed with tensorlayer.
I've tested it several months ago, and it used to work.

Could you try this and see what's in the output?
`tl train example/tutorial_imagenet_inceptionV3_distributed.py`

**Comment by jorgemf** [comment]
@li-zemin both workers finished by themselves because it seems both are set as master. It is something weird with the environment variables (what bash are you using to launch the program?). What version of tensorlayer are you using? I am going to test it again.

Tensorflow is compiled with GRPC so I think this is not the cause.

**Comment by li-zemin** [comment]
@jorgemf Hello, I launched the program on the platform of ubuntu16.4, my tensorlayer version is 1.8.4. Thanks！ Maybe the problem was caused by the network settings, rather than the GRPC.

**Comment by DEKHTIARJonathan** [comment]
If it is working fine, please close the issue ;)
